Vagrant.configure("2") do |config|
        # docker_server for docker
        config.vm.define "docker-centos" do |cfg|
                cfg.vm.box = "generic/centos7"
                cfg.vm.provider "virtualbox" do |vb|
                        vb.name = "docker-centos"
                        vb.cpus = 2
                        vb.memory = 2048
			vb.gui = true
                end
                cfg.vm.host_name = "centos.example.com"
                cfg.vm.network "private_network", ip: "192.168.50.10"
                cfg.vm.provision "shell", path: "ssh_conf.sh", privileged: true
                cfg.vm.provision "shell", path: "add_hosts.sh"
               cfg.vm.provision "shell", path: "docker_install.sh", privileged: true
        end
end
